Read Data

In [1]:
import pandas as pd

In [2]:
DATA_FOLDER = f'Example01/Data'
OUTPUTS_FOLDER = f'Example01/Outputs'

In [3]:
# no train test-split is done on purpose for sake of this example

train_data = pd.read_csv(f"{DATA_FOLDER}/train.csv")

In [4]:
train_data.head(10)

a   b  result
0  1   1       1
1  1   2       2
2  1   3       3
3  1   4       4
4  1   5       5
5  1   6       6
6  1   7       7
7  1   8       8
8  1   9       9
9  1  10      10

Train Model

In [5]:
from sklearn import tree
from sklearn import svm
import numpy as np

In [6]:
X = train_data[['a', 'b']]
y = train_data[['result']]

In [7]:
X.head()

a  b
0  1  1
1  1  2
2  1  3
3  1  4
4  1  5

In [8]:
y.head()

result
0       1
1       2
2       3
3       4
4       5

In [9]:
clf = tree.DecisionTreeRegressor()
#clf = svm.SVR()

clf = clf.fit(X, y)

Measure Accuracy

In [10]:
from sklearn.metrics import accuracy_score

test_data = pd.read_csv(f"{DATA_FOLDER}/test.csv")
X_test = test_data[['a', 'b']]
y_true = test_data[['result']]

y_pred = clf.predict(X_test)
y_pred = np.around(y_pred, decimals=0)

accuracy_score(y_true, y_pred)

1.0

Custom Predictions

In [11]:
clf.predict([[5, 2]])

array([10.])

In [12]:
clf.predict([[3, 8]])

array([24.])

In [13]:
clf.predict([[7, 4]])

array([28.])

Save Tree into PDF File

In [14]:
import graphviz
dot_data = tree.export_graphviz(clf, out_file=None)
graph = graphviz.Source(dot_data)
graph.render(f'{OUTPUTS_FOLDER}/tree')

'Example01/Outputs/tree.pdf'